import { FieldType, defineObject } from 'twenty-sdk/define';

import {
  CALL_LOG_DATE_FIELD_ID,
  CALL_LOG_DIRECTION_FIELD_ID,
  CALL_LOG_DIRECTIONS,
  CALL_LOG_DURATION_FIELD_ID,
  CALL_LOG_OBJECT_UNIVERSAL_IDENTIFIER,
  CALL_LOG_OUTCOME_FIELD_ID,
  CALL_LOG_OUTCOMES,
  CALL_LOG_RECORDING_URL_FIELD_ID,
  CALL_LOG_SUMMARY_FIELD_ID,
} from 'src/constants/universal-identifiers';

export default defineObject({
  universalIdentifier: CALL_LOG_OBJECT_UNIVERSAL_IDENTIFIER,
  nameSingular: 'callLog',
  namePlural: 'callLogs',
  labelSingular: 'Call Log',
  labelPlural: 'Call Logs',
  description: 'A logged phone call with a seller, buyer, or other contact',
  icon: 'IconPhoneCall',
  isSearchable: true,
  labelIdentifierFieldMetadataUniversalIdentifier: CALL_LOG_DATE_FIELD_ID,
  fields: [
    {
      universalIdentifier: CALL_LOG_DATE_FIELD_ID,
      type: FieldType.DATE_TIME,
      name: 'callDate',
      label: 'Call Date',
      icon: 'IconCalendar',
      isNullable: true,
    },
    {
      universalIdentifier: CALL_LOG_DIRECTION_FIELD_ID,
      type: FieldType.SELECT,
      name: 'direction',
      label: 'Direction',
      icon: 'IconArrowRight',
      isNullable: true,
      options: CALL_LOG_DIRECTIONS.map((direction, index) => ({
        id: `c1000001-0001-4000-8000-${String(index).padStart(12, '0')}`,
        value: direction.value,
        label: direction.label,
        position: direction.position,
        color: direction.color,
      })),
    },
    {
      universalIdentifier: CALL_LOG_OUTCOME_FIELD_ID,
      type: FieldType.SELECT,
      name: 'outcome',
      label: 'Outcome',
      icon: 'IconCheck',
      isNullable: true,
      options: CALL_LOG_OUTCOMES.map((outcome, index) => ({
        id: `c1000002-0001-4000-8000-${String(index).padStart(12, '0')}`,
        value: outcome.value,
        label: outcome.label,
        position: outcome.position,
        color: outcome.color,
      })),
    },
    {
      universalIdentifier: CALL_LOG_DURATION_FIELD_ID,
      type: FieldType.NUMBER,
      name: 'durationSeconds',
      label: 'Duration (seconds)',
      icon: 'IconClock',
      isNullable: true,
    },
    {
      universalIdentifier: CALL_LOG_SUMMARY_FIELD_ID,
      type: FieldType.RICH_TEXT,
      name: 'summary',
      label: 'Call Summary',
      icon: 'IconMessage',
      isNullable: true,
    },
    {
      universalIdentifier: CALL_LOG_RECORDING_URL_FIELD_ID,
      type: FieldType.LINKS,
      name: 'recordingUrl',
      label: 'Recording',
      icon: 'IconMicrophone',
      isNullable: true,
    },
  ],
});
