import { FieldType, defineObject } from 'twenty-sdk/define';

import {
  INFRA_ASSESSED_DATE_FIELD_ID,
  INFRA_ESTIMATED_TIMELINE_FIELD_ID,
  INFRA_FIBER_DISTANCE_FIELD_ID,
  INFRA_INTERCONNECTION_STATUS_FIELD_ID,
  INFRA_NOTES_FIELD_ID,
  INFRA_SUBSTATION_DISTANCE_FIELD_ID,
  INFRA_TRANSMISSION_DISTANCE_FIELD_ID,
  INFRA_WATER_ACCESS_FIELD_ID,
  INFRASTRUCTURE_SIGNAL_OBJECT_UNIVERSAL_IDENTIFIER,
  INTERCONNECTION_STATUSES,
  WATER_ACCESS_OPTIONS,
} from 'src/constants/universal-identifiers';

export default defineObject({
  universalIdentifier: INFRASTRUCTURE_SIGNAL_OBJECT_UNIVERSAL_IDENTIFIER,
  nameSingular: 'infrastructureSignal',
  namePlural: 'infrastructureSignals',
  labelSingular: 'Infrastructure Signal',
  labelPlural: 'Infrastructure Signals',
  description:
    'Power/fiber/water proximity and interconnection status for hyperscale disposition scoring',
  icon: 'IconBolt',
  isSearchable: true,
  labelIdentifierFieldMetadataUniversalIdentifier:
    INFRA_INTERCONNECTION_STATUS_FIELD_ID,
  fields: [
    {
      universalIdentifier: INFRA_INTERCONNECTION_STATUS_FIELD_ID,
      type: FieldType.SELECT,
      name: 'interconnectionStatus',
      label: 'Interconnection Status',
      icon: 'IconPlugConnected',
      defaultValue: "'UNCONFIRMED'",
      options: INTERCONNECTION_STATUSES.map((status, index) => ({
        id: `a4000007-0001-4000-8000-${String(index).padStart(12, '0')}`,
        value: status.value,
        label: status.label,
        position: status.position,
        color: status.color,
      })),
    },
    {
      universalIdentifier: INFRA_SUBSTATION_DISTANCE_FIELD_ID,
      type: FieldType.NUMBER,
      name: 'substationDistanceMiles',
      label: 'Substation Distance (mi)',
      icon: 'IconRulerMeasure',
      isNullable: true,
    },
    {
      universalIdentifier: INFRA_TRANSMISSION_DISTANCE_FIELD_ID,
      type: FieldType.NUMBER,
      name: 'transmissionLineDistanceMiles',
      label: 'Transmission Line Distance (mi)',
      icon: 'IconRulerMeasure',
      isNullable: true,
    },
    {
      universalIdentifier: INFRA_FIBER_DISTANCE_FIELD_ID,
      type: FieldType.NUMBER,
      name: 'fiberDistanceMiles',
      label: 'Fiber Distance (mi)',
      icon: 'IconRulerMeasure',
      isNullable: true,
    },
    {
      universalIdentifier: INFRA_WATER_ACCESS_FIELD_ID,
      type: FieldType.SELECT,
      name: 'waterAccess',
      label: 'Water Access',
      icon: 'IconDroplet',
      isNullable: true,
      options: WATER_ACCESS_OPTIONS.map((option, index) => ({
        id: `a4000008-0001-4000-8000-${String(index).padStart(12, '0')}`,
        value: option.value,
        label: option.label,
        position: option.position,
        color: option.color,
      })),
    },
    {
      universalIdentifier: INFRA_ESTIMATED_TIMELINE_FIELD_ID,
      type: FieldType.NUMBER,
      name: 'estimatedTimelineMonths',
      label: 'Estimated Interconnection Timeline (months)',
      icon: 'IconClock',
      isNullable: true,
    },
    {
      universalIdentifier: INFRA_ASSESSED_DATE_FIELD_ID,
      type: FieldType.DATE,
      name: 'assessedDate',
      label: 'Assessed Date',
      icon: 'IconCalendar',
      isNullable: true,
    },
    {
      universalIdentifier: INFRA_NOTES_FIELD_ID,
      type: FieldType.TEXT,
      name: 'notes',
      label: 'Notes',
      icon: 'IconNotes',
      isNullable: true,
    },
  ],
});
