import { FieldType, defineObject } from 'twenty-sdk/define';

import {
  PROPERTY_ACREAGE_FIELD_ID,
  PROPERTY_ADDRESS_FIELD_ID,
  PROPERTY_APN_FIELD_ID,
  PROPERTY_CAD_LAND_MARKET_VALUE_FIELD_ID,
  PROPERTY_CLASS_FIELD_ID,
  PROPERTY_COUNTY_FIELD_ID,
  PROPERTY_CURRENT_USE_FIELD_ID,
  PROPERTY_GIS_LINK_FIELD_ID,
  PROPERTY_LEGAL_DESC_FIELD_ID,
  PROPERTY_OBJECT_UNIVERSAL_IDENTIFIER,
  PROPERTY_OCCUPANCY_FIELD_ID,
  PROPERTY_SQFT_FIELD_ID,
  PROPERTY_YEAR_BUILT_FIELD_ID,
  PROPERTY_ZONING_FIELD_ID,
  PROPERTY_ZONING_TRAJECTORY_FIELD_ID,
  ZONING_TRAJECTORIES,
} from 'src/constants/universal-identifiers';

export default defineObject({
  universalIdentifier: PROPERTY_OBJECT_UNIVERSAL_IDENTIFIER,
  nameSingular: 'property',
  namePlural: 'properties',
  labelSingular: 'Property',
  labelPlural: 'Properties',
  description: 'A real estate parcel or asset',
  icon: 'IconBuildingSkyscraper',
  isSearchable: true,
  labelIdentifierFieldMetadataUniversalIdentifier: PROPERTY_ADDRESS_FIELD_ID,
  fields: [
    {
      universalIdentifier: PROPERTY_ADDRESS_FIELD_ID,
      type: FieldType.ADDRESS,
      name: 'propertyAddress',
      label: 'Property Address',
      icon: 'IconMapPin',
    },
    {
      universalIdentifier: PROPERTY_APN_FIELD_ID,
      type: FieldType.TEXT,
      name: 'apn',
      label: 'APN / Parcel ID',
      icon: 'IconHash',
      isNullable: true,
    },
    {
      universalIdentifier: PROPERTY_COUNTY_FIELD_ID,
      type: FieldType.TEXT,
      name: 'county',
      label: 'County',
      icon: 'IconMap',
      isNullable: true,
    },
    {
      universalIdentifier: PROPERTY_LEGAL_DESC_FIELD_ID,
      type: FieldType.TEXT,
      name: 'legalDescription',
      label: 'Legal Description',
      icon: 'IconFileText',
      isNullable: true,
    },
    {
      universalIdentifier: PROPERTY_CLASS_FIELD_ID,
      type: FieldType.SELECT,
      name: 'propertyClass',
      label: 'Property Class',
      icon: 'IconCategory',
      defaultValue: "'LAND'",
      options: [
        { id: 'b1000001-0001-4000-8000-000000000001', value: 'LAND', label: 'Land', position: 0, color: 'green' },
        { id: 'b1000001-0001-4000-8000-000000000002', value: 'COMMERCIAL', label: 'Commercial', position: 1, color: 'blue' },
        { id: 'b1000001-0001-4000-8000-000000000003', value: 'INDUSTRIAL', label: 'Industrial', position: 2, color: 'orange' },
        { id: 'b1000001-0001-4000-8000-000000000004', value: 'MIXED_USE', label: 'Mixed Use', position: 3, color: 'purple' },
      ],
    },
    {
      universalIdentifier: PROPERTY_ACREAGE_FIELD_ID,
      type: FieldType.NUMBER,
      name: 'acreage',
      label: 'Acreage',
      icon: 'IconRulerMeasure',
      isNullable: true,
    },
    {
      universalIdentifier: PROPERTY_SQFT_FIELD_ID,
      type: FieldType.NUMBER,
      name: 'buildingSqFt',
      label: 'Building Sq Ft',
      icon: 'IconDimensions',
      isNullable: true,
    },
    {
      universalIdentifier: PROPERTY_ZONING_FIELD_ID,
      type: FieldType.TEXT,
      name: 'zoning',
      label: 'Zoning',
      icon: 'IconBuildingCommunity',
      isNullable: true,
    },
    {
      universalIdentifier: PROPERTY_CURRENT_USE_FIELD_ID,
      type: FieldType.TEXT,
      name: 'currentUse',
      label: 'Current Use',
      icon: 'IconHome',
      isNullable: true,
    },
    {
      universalIdentifier: PROPERTY_OCCUPANCY_FIELD_ID,
      type: FieldType.SELECT,
      name: 'occupancyStatus',
      label: 'Occupancy Status',
      icon: 'IconDoor',
      isNullable: true,
      options: [
        { id: 'b1000002-0001-4000-8000-000000000001', value: 'VACANT', label: 'Vacant', position: 0, color: 'gray' },
        { id: 'b1000002-0001-4000-8000-000000000002', value: 'OWNER_OCCUPIED', label: 'Owner Occupied', position: 1, color: 'blue' },
        { id: 'b1000002-0001-4000-8000-000000000003', value: 'TENANT_OCCUPIED', label: 'Tenant Occupied', position: 2, color: 'green' },
        { id: 'b1000002-0001-4000-8000-000000000004', value: 'UNKNOWN', label: 'Unknown', position: 3, color: 'orange' },
      ],
    },
    {
      universalIdentifier: PROPERTY_YEAR_BUILT_FIELD_ID,
      type: FieldType.NUMBER,
      name: 'yearBuilt',
      label: 'Year Built',
      icon: 'IconCalendar',
      isNullable: true,
    },
    {
      universalIdentifier: PROPERTY_GIS_LINK_FIELD_ID,
      type: FieldType.LINKS,
      name: 'gisLink',
      label: 'GIS / Map Link',
      icon: 'IconMap2',
      isNullable: true,
    },
    {
      // Texas is a non-disclosure state, so sale prices are not public but the
      // appraisal district's land market value is. It is the only per-parcel
      // valuation anchor available at offer time.
      universalIdentifier: PROPERTY_CAD_LAND_MARKET_VALUE_FIELD_ID,
      type: FieldType.CURRENCY,
      name: 'cadLandMarketValue',
      label: 'CAD Land Market Value',
      icon: 'IconReceiptTax',
      isNullable: true,
    },
    {
      universalIdentifier: PROPERTY_ZONING_TRAJECTORY_FIELD_ID,
      type: FieldType.SELECT,
      name: 'zoningTrajectory',
      label: 'Zoning Trajectory',
      icon: 'IconTrendingUp',
      defaultValue: "'UNKNOWN'",
      options: ZONING_TRAJECTORIES.map((trajectory, index) => ({
        id: `b1000003-0001-4000-8000-${String(index).padStart(12, '0')}`,
        value: trajectory.value,
        label: trajectory.label,
        position: trajectory.position,
        color: trajectory.color,
      })),
    },
  ],
});
